spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: "041104"
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.mint.pojo
  mapperLocations: classpath:mybatis/*.xml
server:
  port: 8081